### ISSUE TITLE
A WebAssembly version of HarfBuzz

### ISSUE THREAD

**Issue by photopea** [harfbuzz/harfbuzzjs#10]
Hi guys, I am developing a free web-based photo editor www.Photopea.com , which is used by around 100 000 people a day. It lets people do image editing, including inserting text into a picture.

As there is no sufficient OpenType parser and layout engine in Javascript, I made my own called [Typr.js](https://github.com/photopea/Typr.js). It is quite advanced and can handle e.g. Arabic text. I also use [this JS implementation of BIDI algorithm](https://github.com/bbc/unicode-bidirectional). 

As more and more people use Photopea, I have to extend Typr.js . Currently, I am adding the support for Urdu and Khmer layout. I am often staring at OpenType specification for 5 - 10 hours, without writing a single line of code, only trying to understand what they mean. I would be more than happy to drop Typr.js and use an alternative, if there was any.

Would you be able to provide a WebAssembly version of your library to the public, while documenting it and maintaining it? I am ready to pay 5k - 10k USD for it. It is also important, that the library is not too large (e.g. 150-200kB zipped), as every person has to download it when starting Photopea.

**Comment by ebraminio** [comment]
Transferred the issue to harfbuzz/harfbuzzjs to have access to all the information here easier.

@photopea here is our latest work using `wasm-opt` optimization, [hb.wasm.zip](https://github.com/harfbuzz/harfbuzzjs/files/3364662/hb.wasm.zip) its demo is here https://harfbuzz.github.io/harfbuzzjs/ and the code you can easily adopt from which is similar to yours is here: https://github.com/harfbuzz/harfbuzzjs/blob/master/examples/nohbjs.html the difference is mostly removal of initial underscores from function names, removal of `hb_direction_from_string` (which you weren't using IIRC) and removal of `hb_buffer_serialize`

Here is of course emscripten result also that may you can adopt easier but I haven't tested it and I don't recommend: [harfbuzzjs.zip](https://github.com/harfbuzz/harfbuzzjs/files/3364664/harfbuzzjs.zip)

@kripken: Ok, this is the result with: `emcc --profiling-funcs` (my distro's emscripten which apparently matches your numbers)

![image](https://user-images.githubusercontent.com/833473/60755986-f3180480-a00c-11e9-8433-b014dc6ef7df.png)

![image](https://user-images.githubusercontent.com/833473/60755837-d975bd80-a00a-11e9-87a1-e27e5b0eeab3.png)

```
-rw-r--r-- 1 ebrahim  309K Jul  6 16:25 a.out.wasm
-rw-r--r-- 1 ebrahim  6.7K Jul  6 16:25 a.out.js
```

Which is better than: (but note the size impact --profiling-funcs had)

![image](https://user-images.githubusercontent.com/833473/60755852-f4e0c880-a00a-11e9-873d-ebe99f361a41.png)

```
-rw-r--r-- 1 ebrahim  183K Jul  6 16:29 a.out.wasm
-rw-r--r-- 1 ebrahim  6.7K Jul  6 16:29 a.out.js
```

But what I like and meant for correct symbol names was this:

![image](https://user-images.githubusercontent.com/833473/60755867-1e99ef80-a00b-11e9-8953-7e4ae481a0b4.png)

![image](https://user-images.githubusercontent.com/833473/60755883-6f114d00-a00b-11e9-811d-c8735b510701.png)

```-rwxr-xr-x 1 ebrahim vdr 178K Jul  6 16:05 hb.wasm```

**Comment by kripken** [comment]
@ebraminio Thanks, I think I see now, `--profiling-funcs` keeps full function name info, which is why it's so big (all internal non-exported function names are kept around too). Seems you want just the export names to not be minified? Is the reason you want the unminified export names that you want to call them directly instead of through emscripten's JS code?

Emscripten automatically minifies exports (and imports) in `-O3` and above. We don't have an option to specifically disable that atm, as we assume that if we emit both js and wasm that we can do optimizations on that pair together (like minifying those imports and exports, and also metadce, etc.). However, we have an option to emit just wasm, in which case you must provide all the js runtime yourself. That's not recommended for most projects since the JS is non-trivial, but maybe it's worth trying here. To try it just do `-o name.wasm`. With that I get this:
```shell
$ ls -alh name.wasm
-rw-rw-r-- 1 alon alon 183K Jul  6 06:33 name.wasm
$ wasm-dis name.wasm | grep export
 (export "hb_blob_create" (func $418))
 (export "hb_blob_destroy" (func $28))
 (export "free" (func $10))
 (export "hb_blob_get_length" (func $985))
 (export "malloc" (func $288))
 (export "hb_buffer_create" (func $520))
 (export "hb_buffer_destroy" (func $1210))
 (export "hb_buffer_set_direction" (func $1205))
 (export "hb_buffer_get_length" (func $1193))
 (export "hb_buffer_get_glyph_infos" (func $1187))
 (export "hb_buffer_get_glyph_positions" (func $504))
 (export "hb_buffer_guess_segment_properties" (func $1179))
 (export "hb_buffer_add_utf8" (func $1170))
 (export "hb_face_create" (func $1027))
 (export "hb_face_destroy" (func $468))
 (export "hb_font_create" (func $948))
 (export "hb_font_destroy" (func $413))
 (export "hb_font_set_scale" (func $877))
 (export "hb_shape" (func $1068))
 (export "__errno_location" (func $1067))
 (export "dynCall_vi" (func $1060))
```

**Comment by yisibl** [comment]
@photopea 

> Accessing system fonts from a browser will probably never happen. Mainly because people are too scared of fingerprinting (a list of fonts in your OS lets the website know that it is you, no matter if you use Incognito mode, VPN etc.).

Chrome has experimental support: https://bugs.chromium.org/p/chromium/issues/detail?id=535764#c67

**Comment by yisibl** [comment]
@ebraminio 
> https://github.com/harfbuzz/harfbuzzjs/issues/10#issuecomment-507573424
> our wasm builds have so simple sbrk that can't grow their memory based on need

Is there a way to dynamically increase the memory? For example, when doing font subsets on the server side of node.js, you may encounter very large font files, and often prompt that there is insufficient memory.

**Comment by ebraminio** [comment]
@yisibl ideally dynamic memory increase should happen in sbrk https://github.com/harfbuzz/harfbuzzjs/blob/c2b670388cd11e7c27f21c19f417cc5fee0d6b06/libc/malloc.cc#L8 using the line you mentioned, guess I couldn't find a way to coordinate that with current code but is possible definitely.

**Comment by yisibl** [comment]
@ebraminio It seems there is hope to support dynamic memory increase.
