### ISSUE TITLE
"Uncaught (in promises) TypeError" with 0.4.x from browser

### ISSUE THREAD

**Issue by MattMatic** [harfbuzz/harfbuzzjs#109]
I have projects that work with HBJS 0.3.6 (hbjs.js and hb.wasm).

However, updating both hbjs.js + hb.wasm to version 0.4.0+ produces an error:

> `Uncaught (in promise) TypeError: WebAssembly.instantiate(): Imports argument must be present and must be an object`

_This even happens with the repository `examples/nohbjs.html` and `examples/hbjs.example.html` with no modifications._

Details:
- Occurs with any 0.4.x
- Win11Pro, Edge
- Occurs with local html file (& remote hb.wasm), or running from local web server.
- FWIW, projects are single HTML file with JavaScript, and nothing extra, using same `WebAssembly.instantiate` as in HBJS `Demo/index.html`
- Fails also with the `WebAssembly.instantateStreaming` method outlined in README.md
- (Similar error with Safari - only with 0.4.x, not 0.3.6)

Any clues would be very helpful! Thank you 😊

**Comment by khaledhosny** [comment]
I probably broke it with #97. I don’t really understand much of this, I’m afraid.

**Comment by MattMatic** [comment]
More detail on the error: `Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #0 "wasi_snapshot_preview1": module is not an object or function`

The `wasi_snapshot_preview1` is new to 0.4.x. I can see it, along with some other hooks, in a hex dump of `hb.wasm`,

But it might be due to including something that needs a standard file I/O hook, or some other environment hook for standard system calls. Trying to understand it all myself! 😊

**Comment by khaledhosny** [comment]
They are run by `npm test`, and there is a couple of other scripts that are run by `node` directly (see the github workflow file for the sequence of commands used for testing)

**Comment by MattMatic** [comment]
Just a small update... I haven't had much time recently.

Now have a working Dockerfile that correctly builds and runs `npm test` (in both Windows cmd and WSL2 terminal).
So, I feel that's much a more stable environment... 😎
(Should be able to fork and submit at some point, or post on this thread)

But similar error remains: "Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #0 "env": module is not an object or function" 😟

So, at least I can progress to working out the JavaScript.

Unless anyone else can assist? 😊

**Comment by MattMatic** [comment]
Some updates...

`nohbjs.html` also fails in the browser, unless hb.wasm is built with `-s STANDALONE_WASM=1` in the em++ parameter list.
Without this, "Uncaught (in promise) TypeError: WebAssembly.instantiate(): Imports argument must be present and must be an object" is shown in the browser JavaScript console.

When the standalone flag is added, nohbjs.html produces what seems to be a good output: `[{"g":68,"cl":0,"ax":561,"ay":0,"dx":0,"dy":0},{"g":69,"cl":1,"ax":615,"ay":0,"dx":0,"dy":0},{"g":70,"cl":2,"ax":480,"ay":0,"dx":0,"dy":0}]`


However, the `hbjs.js` now seems to be only compatible with node.js, and not browsers 😟
And it is apparent that `npm test` only tests for node.js, and not the browser use of `hb.wasm`.

Aam enjoying digging into WebAssembly in browsers and WASM assembler... 😏
...but help would be very much appreciated! 😊

**Comment by khaledhosny** [comment]
I think (I have vague recollection) that we need `-s EXPORT_ES6=1` to make the module compatible with browsers, but then we will need to switch from using `require` (with I think is nodejs-only) to using `import`, and last I tried that it needed quite a number of changes to the code and the examples/tests.

**Comment by MattMatic** [comment]
That is very helpful.

I can now see that 0.4.x uses `-s MODULARIZE`. According to the emscripten docs, this wraps things in a promise - so the web page JS load code has to change from what it was for 0.3.x
See: https://emscripten.org/docs/tools_reference/settings_reference.html#modularize
and: https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#interacting-with-an-api-written-in-c-c-from-nodejs (this is specifically NodeJS though)

EXPORT_ES6 will also only work if MODULARIZE is enabled.

I'll try and find time to experiment, but hoping that hb.wasm + hbjs.js can be used as-is, but with different loading code in the html page(s).

**Comment by graphicore** [comment]
I'm using harfbuzzjs with JavaScript modules, maybe my mesures to load it are helpful.

Have a look at this directory: https://github.com/FontBureau/TypeRoof/tree/main/lib/js/vendor/harfbuzzjs
especially this https://github.com/FontBureau/TypeRoof/blob/main/lib/js/vendor/harfbuzzjs/harfbuzz.mjs

There's a simple build script to lift harfbuzzjs to use modules: https://github.com/FontBureau/TypeRoof/blob/main/lib/js/vendor/harfbuzzjs/build.sh

Note, I'm using a fork of harfbuzzjs, but mainly to export other symbols, I'm tracking main but slowly (10 commits behind) https://github.com/graphicore/harfbuzzjs/tree/TypeRoof-main

I'm sorry if this is mot relevant, I'm in a hurry. :-)

**Comment by MattMatic** [comment]
Appreciate everyone's input.

**Update**: _finally_ have worked out how to load hb.wasm into a browser. 😎🎉

Since it's been modularized (with `-s MODULARIZE`), it also requires `hb.js` (which provides the "Module"). The "EXPORT_ES6" is not required.

To clean up the name space, the `-s EXPORT_NAME=createHarfBuzz` can also be used. Rather than using `WebAssembly.instantiateStreaming`, or `.instantiate`, it works something like this:

```js
<script src='hb.js'></script>
<script src='hbjs.js'></script>
<script>
…
let harfBuzzModule; // not really needed with the hbjs wrapper
createHarfBuzz().then(hbmodule=>{
  harfBuzzModule = hbmodule;
  window.hb = hbjs(hbmodule);
   …
  });
});
```

I've done an initial local test with the updated HarfBuzz TINY setting, and all is good within the browser - e.g. script "deva" and language tags of "nep" and "mar" all work fine now. 😊

Have forked this repo and am fixing the build, adding Dockerfile & instructions, and correcting the browser based examples.

**Comment by MattMatic** [comment]
Have forked, updated, and PR'd back to here.

I've also updated my tools that use hb.wasm with the hb.js/hbjs.js combo.
- https://github.com/MattMatic/hbfontcompare
-- https://mattmatic.github.io/hbfontcompare/
- https://github.com/MattMatic/font-compare-word-list 
-- https://mattmatic.github.io/font-compare-word-list/

I haven't update the `gh-pages` branch that houses the demo. It's easily updated, by I forgot to include all branches when I forked 🫢.

Please let me know if I've missed anything else!
