### ISSUE TITLE
When to destroy blob and face

### ISSUE THREAD

**Issue by Harachie** [harfbuzz/harfbuzzjs#14]
Hi HarfBuzz masters,

thank you very much for this awesome library!

Can you please let me know when it's correct/ok to destroy the blob and face?
The code says "/* issue destroy only when you are done with the buffer, not before */" for the create blob method.

I want to cache the font objects for subsequent shaping.
Is it valid to destroy the blob and face and only keep the face once the font has been created?
The c++ version is fine with it I think. But this comment from above makes me wonder ;).

Thank you for your support and kind regards

**Comment by ebraminio** [comment]
Oooh, I am very sorry about it, it was fixed with c2b6703 but I forgot to remove the comment. Thank you so much for pointing it out. Let me know anything you face with the work. Thanks!

**Comment by ebraminio** [comment]
>  Is it valid to destroy the blob and face and only keep the face once the font has been created?

Yes, since c2b6703, AFAIK and as my tests.

**Comment by ebraminio** [comment]
I will also try to provide https://github.com/harfbuzz/harfbuzzjs/blob/master/raqm.js/raqm.html#L79-L83 in the hbjs.js as soon it gets stable in HarfBuzz itself, I believe it will be very useful for the places hbjs is used but feel free to use it just now :)

**Comment by Harachie** [comment]
Thank you very much for clarification! 
I am also looking forward for the raqm stuff! 
It looks super nice and I would love to use the glyph extraction methods as well.

**Comment by ebraminio** [comment]
Oh, here is a working example, https://harfbuzz.github.io/harfbuzzjs/raqm/raqm.html `hbjs_ot_glyph_svg` just is going to be named `hbjs_glyph_svg` if we don't move the whole thing to HarfBuzz itself!

**Comment by Harachie** [comment]
Thank you!
Do I understand it correctly, that raqm will apply the BiDi algorithm and is suitable for mixed unicode text?
Would you also tell me your dev environment?
My crappy Windows cannot build the FriBiDi library, so I need to do it on another machine ;).

**Comment by ebraminio** [comment]
>  Do I understand it correctly, that raqm will apply the BiDi algorithm and is suitable for mixed unicode text?

Correct! It uses fribidi as bidi algorithm.

> Would you also tell me your dev environment?

I use Linux but am leaving this comment using a Windows not on my machine! :)

> cannot build the FriBiDi library, so I need to do it on another machine ;).

It is my fault actually, fribidi source needs some bootstrapping to generate some header files that aren't checkout it in the repo itself with `meson build -Ddocs=false; ninja -Cbuild` meaning `fribidi/build/gen.tab/` and `fribidi/build/lib` are fribidi's compile time generated files, they don't need to be built wasm specifically, just bootstrapped one which our https://github.com/harfbuzz/harfbuzzjs/blob/master/fribidi.js/build.sh should be able to do so, I should've added to command on raqm build also.
