### ISSUE TITLE
Using Harfbuzzjs to determine extents

### ISSUE THREAD

**Issue by nigelgutzmann** [harfbuzz/harfbuzzjs#15]
Hi there, I am working on Lumen5, which is a video creation engine. One of the things we deal with is measuring the extents of words in different fonts, which is useful for things like animations and masks. Basically, we need a precise bounding box of the text that we are rendering. Currently, we render the text inside of a canvas and then analyze the pixels inside the rendered image to find the extents of the rendered text. As you can imagine, this is quite slow.

I am new to harfbuzz, so I'm wondering if we could improve this using harfbuzzjs. I looked through the documentation and can see that you can get extents by calling hb_shape with the correct feature flags set. However, in the javascript all over the place it says that features aren't enabled. Does that mean that this isn't possible to do through harfbuzzjs, or is there something specific that I need to do to get access to it? Would just love a starting spot or some indication of if I am on the correct path or not, thank you!

**Comment by ebraminio** [comment]
Hi, we have `hb_font_get_glyph_extents` API in HarfBuzz, it supposed to be precise bounding box of glyphs AFAIK but I can't assure that personally, it should be checked for the fonts you are going to use, do you like to have it exposed? Thanks!

**Comment by nigelgutzmann** [comment]
That sounds promising! Would it be possible to access that through javascript somehow? I would love to try it out.

**Comment by ebraminio** [comment]
Yeah, sure, which wasm file do you use? And are you using our `hbjs_glyph_svg`?

**Comment by nigelgutzmann** [comment]
We haven't integrated anything yet, but I'm assuming hb.wasm? I can use anything you recommend!

**Comment by ebraminio** [comment]
Oh I see, you're interested on words specially unlike what I thought initially, well, unless you are doing rest of rendering limited to just a controlled font I can say measuring just a word but rendering somewhere else isn't that reliable, but as a starting point, have a look at https://harfbuzz.github.io/harfbuzzjs/ and its source, you can pick its very wasm even, and there https://harfbuzz.github.io/harfbuzzjs/raqm/raqm.html which doesn't use our wrapper but handles bidi and extract glyph contours but that maybe is easier to read or not :) Thanks!

**Comment by nigelgutzmann** [comment]
Thank you! I will give it a try!

**Comment by ebraminio** [comment]
Feel free to keep up updated, thanks :)
