### ISSUE TITLE
Can we have buffer messaging?

### ISSUE THREAD

**Issue by simoncozens** [harfbuzz/harfbuzzjs#16]
Any reason why not? Would help me to have trace functions in harfbuzzjs.

```diff
diff --git a/src/hb-config.hh b/src/hb-config.hh
index fc8d424..1e57ec6 100644
--- a/src/hb-config.hh
+++ b/src/hb-config.hh
@@ -53,7 +53,6 @@
 #define HB_DISABLE_DEPRECATED
 #define HB_NDEBUG
 #define HB_NO_ATEXIT
-#define HB_NO_BUFFER_MESSAGE
 #define HB_NO_BUFFER_SERIALIZE
 #define HB_NO_BITMAP
 #define HB_NO_CFF
```

**Comment by simoncozens** [comment]
OK, sounds like the simplest way is to write a C function `hbjs_shape_with_trace` which takes a buffer and fills it with the tracing output, and expose that like you did with the `hbjs_glyph_svg`.

**Comment by ebraminio** [comment]
moved to harfbuzzjs repo, exactly, thank you very much

**Comment by simoncozens** [comment]
OK, I know what I'm doing now! I've got vsnprintf, and a few other string functions, which also means I can parse features.

**Comment by ebraminio** [comment]
Let me know if anything needed, it should be not easy but possible to mimic, we have different things around like a simple itoa implementation.

**Comment by simoncozens** [comment]
Think I've got everything - do you want any PRs for what I'm doing? (Feature handling, etc.?)

**Comment by ebraminio** [comment]
Sure! Sharing it with others would be excellent, I gave you write permission also so upload a PR so may we can discuss things a little more or push directly anyway. Thanks!

**Comment by ebraminio** [comment]
Hey, just am curious to know what has happened, thanks

**Comment by simoncozens** [comment]
I don't tend to work much on Sundays. :-)

I've got some changes from yesterday; I brought in glyph_to_svg, added sprintf and friends, and added tracing.  Because I had sprintf/etc. I could also add feature parsing. But I've only added that to `shape_with_trace` so far, need to clean it up and add it to `shape`. I still need buffer serialization. When I've got it cleaned up and working I will push a separate branch.

**Comment by ebraminio** [comment]
Ooh, this sounds interesting! I just was worried something bothered you and you were in approach rethinking, let me know if any help is needed

**Comment by simoncozens** [comment]
Have a look in "tracing" branch. It's looking really nice:

```javascript
$ node examples/tracing.node.js
[
  { g: 80, cl: 0, ax: 486, ay: 0, dx: 0, dy: 0 },
  { g: 234, cl: 1, ax: 558, ay: 0, dx: 0, dy: 0 }
]
[
  { m: 'start table GSUB', t: [ [Object], [Object], [Object] ] },
  { m: 'start lookup 24', t: [ [Object], [Object], [Object] ] },
  { m: 'end lookup 24', t: [ [Object], [Object] ] },
  { m: 'end table GSUB', t: [ [Object], [Object] ] },
  { m: 'start table GPOS', t: [ [Object], [Object] ] },
  { m: 'start lookup 1', t: [ [Object], [Object] ] },
  { m: 'end lookup 1', t: [ [Object], [Object] ] },
  { m: 'end table GPOS', t: [ [Object], [Object] ] }
]
```

**Comment by ebraminio** [comment]
wow, niiiiiiiice :)
