### ISSUE TITLE
hb.wasm / harfbuzz.wasm

### ISSUE THREAD

**Issue by simoncozens** [harfbuzz/harfbuzzjs#17]
build.sh builds `harfbuzz.wasm`:

```
wasm-opt -Oz a.out -o harfbuzz.wasm && rm a.out
```

index.js includes `hb.wasm`:

```
  fs.readFile(path.resolve(__dirname, 'hb.wasm'), function (err, data) {
```

**Comment by ebraminio** [comment]
fixed, removed `wasm-opt` call to show how simple the whole thing is just if we avoid a libc.
