### ISSUE TITLE
Can't build project under Fedora 31

### ISSUE THREAD

**Issue by konsoletyper** [harfbuzz/harfbuzzjs#20]
I follow build instruction and get following error message in the console:

```
clang-9: error: unable to execute command: Executable "wasm-ld" doesn't exist!
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ebraminio** [comment]
you should install lld (llvm's linker) from your package manager also, please confirm if that solves it, thanks

**Comment by konsoletyper** [comment]
Yes, that helped. Also it would be great if you mentioned this in README.

**Comment by ebraminio** [comment]
Done https://github.com/harfbuzz/harfbuzzjs/commit/fcea624ccf9dcf4e206ce5a4e3e8ba781e863e09

**Comment by ebraminio** [comment]
Done, https://github.com/harfbuzz/harfbuzzjs/commit/cc4c3fe683002750845114fb5e7af36e4364122c
