### ISSUE TITLE
Usage with text editor

### ISSUE THREAD

**Issue by dakom** [harfbuzz/harfbuzzjs#21]
This isn't exactly a harfbuzz(js) question - but more a community question to see if anyone has worked on an integration.

For example, DraftJS does supply block and inline encoding in such a way that I think it can be fed into harfbuzz (see flow types at https://github.com/facebook/draft-js/tree/master/src/model/encoding)

Has anyone worked on a wysiwyg web text editor, that feeds into harfbuzz and outputs a svg or BitmapData?

Thanks!

**Comment by ebraminio** [comment]
There is a missing part to make such case easy to use as harfbuzz itself isn't enough for a complete experience and you'll need bidi and as harfbuzz itself doesn't do bidi it isn't able to do layout, however, we have provided raqm/fribidi here also and this is all you need to use raqm https://harfbuzz.github.io/harfbuzzjs/raqm/raqm.html note that it doesn't use hbjs.js wrapper and `hbjs_ot_glyph_svg` is renamed to `hbjs_glyph_svg`

**Comment by dakom** [comment]
Wow, that's amazing! 

I think DraftJS does bidi detection on a per-block level, so getting from that to a 1:1 image representation might not need raqm, except maybe to deal with wrapping / line breaks?

Right now I'm more just gathering info and thinking about the ecosystem... great to know that what I'm after is possible, perhaps even easy (with the work you've done here)! Will probably be a couple weeks or so till I start tinkering in code, but I appreciate the quick response on this and the other issue. Thanks again!

**Comment by dakom** [comment]
If anyone knows of text-editors besides DraftJS that give breakdowns that are a better fit for feeding into harfbuzz or raqm, that would be useful info too.

**Comment by ebraminio** [comment]
> I think DraftJS does bidi detection on a per-block level, so getting from that to a 1:1 image representation might not need raqm, except maybe to deal with wrapping / line breaks?

I don't think this would be enough, you need something that does something like https://harfbuzz.github.io/harfbuzzjs/fribidi/ then send text of having same direction (note the numbers there) and script to harfbuzz, you can use raqm but there is a possibility that we support something similar also.

**Comment by ebraminio** [comment]
> Right now I'm more just gathering info and thinking about the ecosystem... 

Sure! We like also be helpful there :) Whole thing is so simple, just clone the project run ./build.sh, you will have a working .wasm without any dependency and easy to initiate, run `examples/hbjs.example.node.js` for example and see its simple code, intended to be easy as that :)
