### ISSUE TITLE
Documentation for demo example

### ISSUE THREAD

**Issue by dakom** [harfbuzz/harfbuzzjs#22]
The demo example seems to be generating a SVG, not just sequencing together glyph images.

Is there some documentation explaining the thought process behind this, and how one might integrate this into their own project?

Thanks!

**Comment by ebraminio** [comment]
You noted the demo is improved :) just call `glyphToPath` from a font object https://github.com/harfbuzz/harfbuzzjs/blob/6525bfb/hbjs.js#L43 note that it uses an experimental API of harfbuzz itself yet no need to worry for that here as we are able to keep the support here.

**Comment by ebraminio** [comment]
https://github.com/harfbuzz/harfbuzzjs/blob/master/examples/hbjs.example.js both shapes and returns glyphs used on the sequence

**Comment by khaledhosny** [comment]
> not just sequencing together glyph images.

You need something to rasterize the glyphs, HarfBuzz does not have one and there is no web API that takes glyph IDs as input, so converting to SVG is a way to use the browser’s SVG renderer to rasterize the glyphs.

**Comment by ebraminio** [comment]
so guess things can be considered resolved here specially as documentation @simoncozens has put on README.md, thanks!
