### ISSUE TITLE
Support OpenType Color Fonts

### ISSUE THREAD

**Issue by yisibl** [harfbuzz/harfbuzzjs#23]
1. Open https://harfbuzz.github.io/harfbuzzjs/
2. Drag and drop this font file：https://www.fontself.com/colorfontweek/2018#playbox

Error message：

```
<svg> attribute viewBox: A negative value is not valid. ("12000 12000 -24000 -24000")
```
This is a OpenType Color Fonts，I hope that the preview can be colored.

![image](https://user-images.githubusercontent.com/2784308/90121266-59ce2c80-dd8e-11ea-8dbb-12bcac86c18b.png)

**Comment by ebraminio** [comment]
We have its support code inside [HarfBuzz APIs](https://github.com/harfbuzz/harfbuzz/blob/1934652/src/hb-ot-color.h#L42-L114) and [here is its demo in C](https://github.com/harfbuzz/harfbuzz/blob/1934652/src/main.cc#L178-L246), just needs someone to add the APIs to [wasm builds](https://github.com/harfbuzz/harfbuzzjs/blob/master/build.sh#L24) then compile the `.wasm` containing the support and port that C code to JS, are you interested on it?

**Comment by yisibl** [comment]
Oh, sorry, it may be a dynamic link, please download it here: https://www.fontself.com/colorfontweek/2018#playbox

I am interested, but I forgot about my C language 😭 .

Moreover, my LLVM has been installed all afternoon, and it has not been installed yet.

**Comment by ebraminio** [comment]
> I am interested, but I forgot about my C language.

No worries, remember that C "mimics" JavaScript's syntax so you should be fine here :) I can help you however with particular questions.

> Is clang that comes with the macOS OK?

I'm not sure but they are usually shipping the outdated versions, just run `build.sh` of this repo and see what happens :) You can always install it from `brew` however, this is what Simon and Khaled has done successfully.

**Comment by yisibl** [comment]
Thanks, does `lld` need to be installed separately?

In addition, ask some questions, and hope to help me answer my doubts.

* What does `.malloc()` in `instance.exports` do?
* What is the difference between `hb_face_create` and `hb_font_create`, and in what scenarios should I use them?
* How to modify the name table and version of the font?

**Comment by ebraminio** [comment]
> Thanks, does `lld` need to be installed separately?

I think `lld` is already the default linker in macOS, you just need maybe an update version (maybe your version already is?) which `wasm-ld` to be have in PATH I think, something is suggested here https://github.com/tinygo-org/tinygo/issues/82#issuecomment-466793964 which shows `lld` in `llvm` package in `brew`.

> What does `.malloc()` in `instance.exports` do?

The way memory allocation works in C, basically guarantees some part of memory can be used for certain work by who requested that amount of memory, and returns address of that part to who has requested it.

> What is the difference between `hb_face_create` and `hb_font_create`, and in what scenarios should I use them?

Take `hb_face_t` as some equivalent of a `.ttf` file (which isn't for font collection, still). `font` is an instance of `face` which has size and variation and other things set.

> How to modify the name table and version of the font?

That isn't easy :) There is something related [here](https://github.com/harfbuzz/harfbuzz/blob/a11db0b/src/hb-uniscribe.cc#L369-L456) but that is private API and harder to read, maybe you can find some other library able to do that, maybe we should do it as a part of subset API or maybe not, it isn't supported currently anyway.

**Comment by yisibl** [comment]
Thank you for your patience.

> That isn't easy :) There is something related here but that is private API and harder to read, maybe you can find some other library able to do that, maybe we should do it as a part of subset API or maybe not, it isn't supported currently anyway.

I think it can be implemented in subset. I am currently maintaining the largest font icon website(https://www.iconfont.cn) in China. We need to generate different versions after font subsets.

I plan to switch the font subset function to **harfbuzzjs**. Currently we rely on opentype.js, but in the scene where CJK fonts are subsetted (font files are usually large, 10MB+), the speed is relatively slow, and **the server's CPU usage is also very high**. Switching to harfbuzzjs should be a big improvement.

We have millions of users and hope this can give you motivation.

**Comment by ebraminio** [comment]
The very subset project is motivated by CJK issues AFAIK, let's ask @garretrieger whether considering your usecase is a possibility, basically turning what we have in [hb-uniscribe](https://github.com/harfbuzz/harfbuzz/blob/a11db0b/src/hb-uniscribe.cc#L369-L456) into a feature, guess will useful for Google Fonts hosting also.

**Comment by yisibl** [comment]
Yes! Very useful!!!

We also have [CJK font hosting service](https://www.iconfont.cn/webfont?spm=a313x.7781069.1998910419.d81ec59f2#!/webfont/index). Performance is currently the bottleneck.

**Comment by yisibl** [comment]
@photopea Are you interested in color fonts? I remember that Typr.js already supports color fonts.

**Comment by photopea** [comment]
Hi, I think Harfbuzz is not for parsing SVG or for extracting the vector shapes of glyphs. I would like that Harfbuzz remains simple and a single-purpose library.

Parsing vector shapes of glyphs can be done with other tools. Photopea and Typr.js already support color fonts.

**Comment by behdad** [comment]
HB has API to fetch SVG for glyph. That's all. A lot more code needs to be written by client to render them.

**Comment by yisibl** [comment]
@ebraminio Subsetting [Playbox-FREE.otf](https://www.fontself.com/colorfontweek/2018#playbox) will become black and white, how to keep the color?

![image](https://user-images.githubusercontent.com/2784308/91327605-51e3a300-e7f8-11ea-811d-129d24fa759a.png)

**Comment by photopea** [comment]
@yisibl What program do you use to render the font? Harfbuzz is just a tool for shaping the text, it does not contain functions to rasterize bézier curves or parse the SVG.

**Comment by ebraminio** [comment]
Weird, COLR/CPAL subset isn't behind any compile flags as I checked now so
should work there, please check if the issue also exists with hb-subset
command line tool shipped with HarfBuzz Linux packages or in win32 package
of https://github.com/harfbuzz/harfbuzz/releases/tag/2.7.1 the latest
release

**Comment by yisibl** [comment]
@ebraminio 

I execute the following command on the Mac, prompt: Unable to open output file

```shell
 hb-subset Playbox-FREE.otf 123ABC
```

**Comment by yisibl** [comment]
@photopea Which problem are you referring to? Subset color fonts or rendering of color fonts on web pages?

**Comment by papandreou** [comment]
@yisibl, try:

```
hb-subset --output-file=... Playbox-FREE.otf 123ABC
```

**Comment by yisibl** [comment]
@papandreou Thanks! This command works, but the color is also lost.
[Playbox-FREE-subset.otf.zip](https://github.com/harfbuzz/harfbuzzjs/files/5134504/Playbox-FREE-subset.otf.zip)

**Comment by khaledhosny** [comment]
The font contains SVG table, hb-subset does not support SVG table (hb-view does not support it either).

**Comment by yisibl** [comment]
@khaledhosny Is there a plan to support SVG table?

**Comment by khaledhosny** [comment]
I don’t know, you need to open an issue in the main repo. But I guess the answer will be the similar to https://github.com/fonttools/fonttools/issues/534,

**Comment by behdad** [comment]
SVG-table subsetting is particularly challenging because it involves modifying XML to rename glyphs. So basically a full-on XML library is needed and then some, to do it correctly. Or we can do a simple job at it using search/replace and not trimming unreachable elements after subsetting.

**Comment by behdad** [comment]
> SVG-table subsetting is particularly challenging because it involves modifying XML to rename glyphs. So basically a full-on XML library is needed and then some, to do it correctly. Or we can do a simple job at it using search/replace and not trimming unreachable elements after subsetting.

Definitely much more doable in fonttools than in HarfBuzz.
