### ISSUE TITLE
How to get or modify the font name table?

### ISSUE THREAD

**Issue by yisibl** [harfbuzz/harfbuzzjs#25]
Can you provide API to get and modify the font name table? This is very useful for icon font.

**Comment by behdad** [comment]
Use fonttools.

**Comment by yisibl** [comment]
Sorry, I am not sure what the positioning of harfbuzzjs is. However, there is still a lack of similar features in Node.js, which can help improve the performance of font processing. Are there any plans to support it? Or where should I start to build the version with the name table?

**Comment by behdad** [comment]
Maybe you can tell is about what your use-case is, so we can (in Dilbert's terms) tell you how to do without what you are asking for.

**Comment by yisibl** [comment]
I need to generate different font files from SVG icon. Therefore, it is necessary to define the information of font related tables, such as various names, copyright information, etc. When the new SVG icon is added to the font, the version information needs to be updated.

harfbuzzjs already has glyphs available, which is great. If I can get these through harfbuzzjs, I can get rid of opentype.js completely.

This is a simple flow chart:
![image](https://user-images.githubusercontent.com/2784308/91191726-b7b42a00-e727-11ea-8d83-4517d1cadad9.png)

**Comment by khaledhosny** [comment]
HarfBuzz is not a font editing library, you will need to use something else like FontTools (if you can use Python, or another JS library).

**Comment by yisibl** [comment]
@khaledhosny Thanks!
