### ISSUE TITLE
subset should export hb_set_destroy method

### ISSUE THREAD

**Issue by dail** [harfbuzz/harfbuzzjs#35]
I have noticed that, in https://github.com/harfbuzz/harfbuzzjs/blob/master/subset/test.cc file, the glyphs created by hb_set_create is destroyed by the hb_set_destroy. 
but in "https://github.com/harfbuzz/harfbuzzjs/blob/master/subset/build.sh", this method is not exported

**Comment by ebraminio** [comment]
Done. Thanks!
