### ISSUE TITLE
memory leak in subset demo

### ISSUE THREAD

**Issue by dail** [harfbuzz/harfbuzzjs#36]
In "https://github.com/harfbuzz/harfbuzzjs/blob/master/subset/test.js", the fontBuffer created by exports.malloc is not destroyed.  The memory should be released by call exports.free method.

**Comment by yisibl** [comment]
This problem is indeed serious.

**Comment by ebraminio** [comment]
@papandreou feel free to consider this isn't issue in your codes as the demo was based on yours apparently. If you are destroying whole wasm machine it probably won't matter much yet better to have this also. Thanks!

**Comment by papandreou** [comment]
@ebraminio, thanks for the ping. I'm not destroying the whole wasm machine, and the heap gets reused between calls to the subsetting. Fixed in https://github.com/papandreou/subset-font/commit/1170630a1cb3be4a5279facc75cecfd5220ede1f

**Comment by ebraminio** [comment]
Turned out it one more issue which is fixed by https://github.com/harfbuzz/harfbuzzjs/commit/d8d54ad7e52f55b3f8c5ede09562d390b872d5b2

Went for fixing it in subset-font and found some other issue added on: https://github.com/papandreou/subset-font/pull/2
