### ISSUE TITLE
Option to configure what to retain in the name table of a font?

### ISSUE THREAD

**Issue by bjrn** [harfbuzz/harfbuzzjs#40]
I'm looking into whether it's possible to retain the font licensing information when subsetting fonts using harfbuzzjs (I'm using harfbuzz through [subset-font](https://github.com/papandreou/subset-font)) I've posted more details in an issue there: 

https://github.com/papandreou/subset-font/issues/7

Is this already a possibility that needs to be exposed as options in the library or does it require extensive changes?

**Comment by ebraminio** [comment]
Left a comment at https://github.com/papandreou/subset-font/issues/7#issuecomment-867506981

**Comment by bjrn** [comment]
Thanks so much for your help — looks like it was possible in harfbuzzjs already — closing this one 👍🏼
