### ISSUE TITLE
Source-Han-Serif subsetting failed

### ISSUE THREAD

**Issue by yisibl** [harfbuzz/harfbuzzjs#44]
I use SourceHanSerifCN-Regular in the [demo](https://harfbuzz.github.io/harfbuzzjs/subset/), and the generated size is larger than the original font.
![image](https://user-images.githubusercontent.com/2784308/128213150-32dce207-3fd8-4b49-b306-ffa5ea2030a2.png)

[subset.zip](https://github.com/harfbuzz/harfbuzzjs/files/6932632/subset.zip)

**Comment by behdad** [comment]
That doesn't mean it failed. Just that it's not as well optimized. Probably because of subroutinization. Adobe contributed the CFF/CFF2 subsetting code; no one left in the project knows that code base, so I can't be sure currently. cc @garretrieger

**Comment by ebraminio** [comment]
@yisibl Guess CFF subset isn't enabled in HB_TINY, what will be the result if you run hb-subset tool instead?

**Comment by yisibl** [comment]
```shell
hb-subset SourceHanSerifCN-Medium.ttf --text=你好123 --output-file=subset.ttf
```
hb-subset is ok.

![image](https://user-images.githubusercontent.com/2784308/128220642-0b1083c8-8a61-4c0f-8edd-d86f5f305e4d.png)

**Comment by ebraminio** [comment]
So maybe desubroutinize flag is set somehow? We aren't touching it here at least https://github.com/harfbuzz/harfbuzzjs/blob/gh-pages/subset/index.html#L27

**Comment by garretrieger** [comment]
Do you have a command line which reproduces the problem? I tried:
```
hb-subset SourceHanSerifCN-Regular.ttf --text=你好123 --output-file=subset.ttf
```

Which results in a subset of size 2856 bytes.

**Comment by garretrieger** [comment]
Also that subset.ttf is not a valid font file.  How did you produce it?

**Comment by garretrieger** [comment]
Looks like some sort of bug in the demo. No matter what font I put in it gets a 26 mb download back. Don't think this is related to harfbuzz. Please re-open if you have a reproduction via harfbuzz.

**Comment by garretrieger** [comment]
Oh sorry, thought this issue was posted in harfbuzz. Re-opening.

**Comment by yisibl** [comment]
Yes, I dragged and downloaded the font file in the demo, I tried other fonts, and it was always 26MB.

**Comment by ebraminio** [comment]
@yisibl was a regression on the demo, my fault, Blob needed a concrete buffer to work upon and subarray views weren't enough for it and 26mb was basically whole heap of the wasm machine.

**Comment by yisibl** [comment]
@ebraminio Thanks for the quick fix.
