### ISSUE TITLE
Upgrade harfbuzz to v3.x

### ISSUE THREAD

**Issue by yisibl** [harfbuzz/harfbuzzjs#46]
The hb-subset API and the harfbuzz-subset library's ABI are now declared stable. Is it time to upgrade to v3.x?

https://github.com/harfbuzz/harfbuzz/releases/tag/3.0.0

**Comment by ebraminio** [comment]
https://github.com/harfbuzz/harfbuzzjs/commit/1e9933bf2da604e8f95b3d9224f8884f29da931f and released 0.2.0 with harfbuzz 3.0.0, the most recent version 3.1.0, needs more work as upstream now uses parts of C++ standard headers https://github.com/harfbuzz/harfbuzz/commit/bbda020cbc99d6a956f21a7fb05bf721fa0f2faf which harfbuzzjs should also adopt somehow maybe by reviving hose in house version of utilities here, but for now guess this is good also.

**Comment by yisibl** [comment]
Thank you for the quick upgrade. If we switch to Emscripten, will there still be problems in 3.1?

**Comment by ebraminio** [comment]
> Thank you for the quick upgrade. If we switch to Emscripten, will there still be problems in 3.1?

Yes, mentioned https://github.com/harfbuzz/harfbuzzjs/issues/47 the project itself started as emscripten builds and removing emscripten lead to being able to remove the js wrapper.

**Comment by ebraminio** [comment]
Opened https://github.com/papandreou/subset-font/issues/12 as unlike the shape, we didn't provide a js wrapper for subset module and most of our subset clients were using subset-font so it will need some work there also.
