### ISSUE TITLE
CFF support is not enabled

### ISSUE THREAD

**Issue by yisibl** [harfbuzz/harfbuzzjs#58]
Open: https://harfbuzz.github.io/harfbuzzjs/

## Use Font
[WenYue_YingHei-JF.otf.zip](https://github.com/harfbuzz/harfbuzzjs/files/8495532/WenYue_YingHei-JF.otf.zip)

```bash
(index):75 Error: <svg> attribute viewBox: A negative value is not valid. ("12000 12000 -24000 -24000")
```

![image](https://user-images.githubusercontent.com/2784308/163563109-e4711dba-5ccd-4538-91d0-54443eda5218.png)

**Comment by khaledhosny** [comment]
This is a font with CFF table and hb.wasm is not built with CFF support, so getting glyph path and extents are not supported. Enabling CFF support increases the file size by about 40KB, so I’m not sure if we want to do this.

**Comment by khaledhosny** [comment]
Thinking more, I’m leaning towards enabling this by default. People who are more file size-conscious should build their own hb.wasm with modified override file to fit their needs.

**Comment by yisibl** [comment]
Yes, in Node.js it doesn't matter much about the size of the wasm file.

Maybe it's possible to build two versions, one with CFF?

**Comment by papandreou** [comment]
A "kitchen sink" build sounds like a good idea, also when it comes to other potentially useful features that might not make the cut otherwise.

**Comment by behdad** [comment]
> A "kitchen sink" build sounds like a good idea, also when it comes to other potentially useful features that might not make the cut otherwise.

I agree a full build would also be interesting.
