### ISSUE TITLE
Add harfbuzz v6 symbols to hb-subset

### ISSUE THREAD

**Issue by luciancooper** [harfbuzz/harfbuzzjs#68]
I believe these symbols ([new in harfbuzz v6](https://harfbuzz.github.io/api-index-6-0-0.html)) should be added to those exported in the [hb-subset.symbols](https://github.com/harfbuzz/harfbuzzjs/blob/main/hb-subset.symbols) file:

[hb_subset_input_pin_axis_location](https://harfbuzz.github.io/harfbuzz-hb-subset.html#hb-subset-input-pin-axis-location)
[hb_subset_input_pin_axis_to_default](https://harfbuzz.github.io/harfbuzz-hb-subset.html#hb-subset-input-pin-axis-to-default)
[hb_subset_preprocess](https://harfbuzz.github.io/harfbuzz-hb-subset.html#hb-subset-preprocess)

Adding these lines to [hb-subset.symbols](https://github.com/harfbuzz/harfbuzzjs/blob/main/hb-subset.symbols) should do it?

```
_hb_subset_input_pin_axis_location
_hb_subset_input_pin_axis_to_default
_hb_subset_preprocess
```

**Comment by luciancooper** [comment]
Realizing now that these symbols are incompatible with compiling harfbuzz with the `-DHB_TINY` flag. To make them work this would have to be added to [config-override-subset.h](https://github.com/harfbuzz/harfbuzzjs/blob/main/config-override-subset.h):

```h
#undef HB_NO_VAR
```

In accordance with the README, if this "extends harfbuzzjs in ways that you think others will also benefit from", this can be pursued, otherwise, this issue should be closed?

**Comment by yisibl** [comment]
@luciancooper Do you have plans to submit a PR?
