### ISSUE TITLE
shape shouldn't be a method but a function of its own, as HarfBuzz itself

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzzjs#8]

**Comment by behdad** [comment]
What is it a method of?

**Comment by ebraminio** [comment]
Oh this is just a minor todo maybe, currently https://github.com/harfbuzz/harfbuzzjs/blob/master/hbjs.js#L80 shape is a buffer object method but better to keep harfbuzz convention maybe and having shape as an independent function
