### ISSUE TITLE
Fribidi wasm build

### ISSUE THREAD

**Issue by petrsimon** [harfbuzz/harfbuzzjs#86]
Hi,
I'm looking for a js library to handle bidi and I've came across bbc/unicode-bidirectional and https://github.com/bbc/unicode-bidirectional/issues/32 which mentions https://harfbuzz.github.io/harfbuzzjs/fribidi/ which doesn't exist anymore. What has happened to it? Many thanks for any pointers.

**Comment by chearon** [comment]
That got removed in f8caad40af9fe7618db69d62f38d4ea4e5adab18

If you want a fast way to find bidi levels in JS, I ported [Tehreer/SheenBidi](https://github.com/Tehreer/SheenBidi) to WebAssembly here: [chearon/itemizer](https://github.com/chearon/itemizer).

**Comment by petrsimon** [comment]
Thanks a lot!
